I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/patriarche.rpy", line 36, in script
    $ textContamination = CycleContamination()
  File "game/patriarche.rpy", line 36, in <module>
    $ textContamination = CycleContamination()
  File "game/script.rpy", line 77, in CycleContamination
    text = "Nouveaux génovores : " + str(nbNouveauxGenovores)
UnboundLocalError: local variable 'nbNouveauxGenovores' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/patriarche.rpy", line 36, in script
    $ textContamination = CycleContamination()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/patriarche.rpy", line 36, in <module>
    $ textContamination = CycleContamination()
  File "game/script.rpy", line 77, in CycleContamination
    text = "Nouveaux génovores : " + str(nbNouveauxGenovores)
UnboundLocalError: local variable 'nbNouveauxGenovores' referenced before assignment

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Tyranides 1.0
Wed Oct 21 20:56:17 2020
