I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    $ niveauFaim = 0
  File "game/script.rpy", line 55, in <module>
    $ niveauFaim = 0
  File "game/script.rpy", line 21, in ajouteReperage
    global niveauReperage, reperageMax
UnboundLocalError: local variable 'niveauReperage' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    $ niveauFaim = 0
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 55, in <module>
    $ niveauFaim = 0
  File "game/script.rpy", line 21, in ajouteReperage
    global niveauReperage, reperageMax
UnboundLocalError: local variable 'niveauReperage' referenced before assignment

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Tyranides 1.0
Sun Sep 27 20:58:24 2020
